## Put comments here that give an overall description of what your
## functions do

## makeCacheMatrix takes an input matrix and defines it as an object
## with functions get, setinv, getinv and set

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  get <- function() x
  setinv <- function(inverse) i <<- inverse
  getinv <- function() i
  list(set = set, get = get, getinv = getinv, setinv = setinv)
}

## cacheSolve takes the name of the object generated by makeCacheMatrix
## and either computes its inverse (if not done already), or grabs its
## inverse from the cache

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  i <- x$getinv()
  if(!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  data <- x$get()
  i <- solve(data)
  x$setinv(i)
  i
}
